<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net10.0-windows;net9.0-windows;net8.0-windows;net472</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>GcSpreadSamplesExplorer</RootNamespace>
    <AssemblyName>GcSpreadSamplesExplorer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Data\Customers.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevBrewLabs.WPF.Spreadsheet\DevBrewLabs.WPF.Spreadsheet.csproj" />
  </ItemGroup>
</Project>