//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaX.CalcEngine.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlphaX.CalcEngine.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A boolean value is expected.
        /// </summary>
        internal static string BoolExpected {
            get {
                return ResourceManager.GetString("BoolExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell range reference is expected..
        /// </summary>
        internal static string CellRangeRefExpected {
            get {
                return ResourceManager.GetString("CellRangeRefExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell reference is expected..
        /// </summary>
        internal static string CellRefExpected {
            get {
                return ResourceManager.GetString("CellRefExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A float value is expected..
        /// </summary>
        internal static string FloatExpected {
            get {
                return ResourceManager.GetString("FloatExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A formula is expected..
        /// </summary>
        internal static string FormulaExpected {
            get {
                return ResourceManager.GetString("FormulaExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula with name &apos;{0}&apos; is already registered..
        /// </summary>
        internal static string FormulaRegisterError {
            get {
                return ResourceManager.GetString("FormulaRegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Equation, {0}..
        /// </summary>
        internal static string Invalid_Equation {
            get {
                return ResourceManager.GetString("Invalid Equation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid formula expression..
        /// </summary>
        internal static string InvalidFormula {
            get {
                return ResourceManager.GetString("InvalidFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid formula arguments..
        /// </summary>
        internal static string InvalidFormulaArgs {
            get {
                return ResourceManager.GetString("InvalidFormulaArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Equation, not all operators have correct number of operands..
        /// </summary>
        internal static string InvalidOperandsCount {
            get {
                return ResourceManager.GetString("InvalidOperandsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operator..
        /// </summary>
        internal static string InvalidOperator {
            get {
                return ResourceManager.GetString("InvalidOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A number is expected..
        /// </summary>
        internal static string NumberExpected {
            get {
                return ResourceManager.GetString("NumberExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An operator is expected..
        /// </summary>
        internal static string OperatorExpected {
            get {
                return ResourceManager.GetString("OperatorExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A string is expected.
        /// </summary>
        internal static string StringExpected {
            get {
                return ResourceManager.GetString("StringExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown formula, {0}..
        /// </summary>
        internal static string UnknownFormula {
            get {
                return ResourceManager.GetString("UnknownFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown operator..
        /// </summary>
        internal static string UnknownOperator {
            get {
                return ResourceManager.GetString("UnknownOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A variable name is expected..
        /// </summary>
        internal static string VariableExpected {
            get {
                return ResourceManager.GetString("VariableExpected", resourceCulture);
            }
        }
    }
}
